spring:
  profiles: common

tencent:
  map:
    key: NLJBZ-3NCCJ-W4NFT-KIUMF-ONTQ3-MEF6Y
  cloud:
    appId: 1311457311
    secretId: AKIDqZ6MPEpHXbS6WigP4WjhT2NTM3Z0Ndlt
    secretKey: AKIDqZ6MPEpHXbS6WigP4WjhT2NTM3Z0Ndlt
    region-public: ap-nanjing
    bucket-public: hxds-public-1311457311
    region-private: ap-shanghai
    bucket-private: hxds-private-1311457311

wx:
  app-id: wx38deacbf93d0f5db
  app-secret: 764532f6f7f3969bc72d2b284fc4a916
  mch-id: 1514785841 #商户号（课程QQ群共享文件中获取）
  key: 123 #（课程QQ群共享文件中获取）
  cert-path: F:/18712174060wws_.pem #商户数字证书文件路径（课程QQ群共享文件中获取）

minio:
  endpoint: http://49.235.217.7:9000
  access-key: root
  secret-key: abc123456

