spring:
  profiles: common

tencent:
  map:
    key: XXXXX
  cloud:
    appId: XXXX
    secretId: XXXX
    secretKey: XXXXX
    region-public: XXXX
    bucket-public: XXXX
    region-private: XXXX
    bucket-private: XXXX
    face:
      groupName: jmdj
      region: ap-beijing

wx:
  app-id: XXXX
  app-secret: XXXX
  mch-id: XXX #商户号（课程QQ群共享文件中获取）
  key: 123 #（课程QQ群共享文件中获取）
  cert-path: F:/18712174060wws_.pem #商户数字证书文件路径（课程QQ群共享文件中获取）

minio:
  endpoint: http://49.235.217.7:9000
  access-key: root
  secret-key: abc123456

